apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pz3b
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0015-tenant/tkrw-pr712-0075-0015-app/devfile-sample-pz3b@sha256:e33d3c080c049f1752788d05fd07cf26beadfe247f0c99fc73edd7c71cd67a84
        name: my-nodejs
        resources: {}
status: {}
